language: swift # or objective-c
osx_image: xcode8
script:
  - xcodebuild -scheme SwiftExample -workspace SwiftExample.xcworkspace -sdk iphonesimulator -destination '43B41BC6-BECD-4162-B7A5-D6B839C5ED32' build test
after_success:
  - bash <(curl -s https://codecov.io/bash)